### ISSUE TITLE
the application is stuck in the loading scerren

### ISSUE THREAD

**Issue by vellt** [satsin06/notes-getx#2]
A getx requires WidgetsFlutterBinding.ensureInitialized();. Without this, the application will not load and will throw an error. I sent the fix in a pull request.

`E/flutter (20738): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Binding has not yet been initialized.`

**Comment by satsin06** [comment]
Thanks for the the update. 😄
